### ISSUE TITLE
执行 composer require orzcc/taobao-top-client报错

### ISSUE THREAD

**Issue by TerryChan** [orzcc/taobao-top-client#10]
为什么我在执行 composer require orzcc/taobao-top-client后报下面的错误呢?

[InvalidArgumentException]
  Could not find package orzcc/taobao-top-client at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

我的环境Lumen 5.2.9，  PHP5.5.12

**Comment by qiufeng5LIFE** [comment]
請問你解決沒？我也一直安裝不了，也是你的這個報錯，我的是laravel 5,5

**Comment by flutterbest** [comment]
"orzcc/taobao-top-client": "dev-master",

**Comment by flutterbest** [comment]
添加到你的composer.json  ，然后composer  update
