### ISSUE TITLE
淘宝客接口生成返利地址

### ISSUE THREAD

**Issue by xcaptain** [orzcc/taobao-top-client#3]
Hi，虽然和这个项目不相关，但是能否指教一下如何调用淘宝接口生成返利地址呢，也给你发邮件请教了，谢谢了

**Comment by orzcc** [comment]
返利接口的申请淘宝已经停止好久了，很难拿到！黑市价也抬得很高，我自己都没有。

**Comment by xcaptain** [comment]
https://open.taobao.com/docs/api.htm?spm=a219a.7629065.0.0.ddHDAv&apiId=26619
这个接口生成的click_url像是返利地址，但是并不起作用

难道现在要生成可用的返利地址只能通过阿里妈妈后台来做？

**Comment by orzcc** [comment]
原来你指的不是返利的事情。淘宝客链接转换 api 是有的，但是申请也需要一定条件：http://club.alimama.com/read-htm-tid-6573218.html

> 淘宝客链接API
> taobao.tbk.item.convert 淘宝客商品链接转换
> 淘宝客商品链接转换接口。根据商品数字id返回该商品的淘宝客推广链接。
> 
> taobao.tbk.shop.convert 淘宝客店铺链接转换
> 淘宝客店铺链接转换接口。根据卖家id返回该卖家的淘宝客推广链接。

**Comment by louiegit** [comment]
taobao.tbk.item.convert 淘宝客商品链接转换 这个不是要一定的用户量吗？那初级用户不可以申请吧？

**Comment by orzcc** [comment]
> 需要一定量满足条件了才可以申请

**Comment by JxbSir** [comment]
@louiegit @orzcc 都没有淘宝客链接，怎么去达到他们需要满足的条件
